LANGUAGES = {
    "zh": {
        "app_title": "S2T2S",
        "app_subtitle": "聲音-文本轉換和摘要系統",
        "instructions_title": "說明",
        "instructions": [
            "1. 上傳您的音頻文件 (.mp3, .m4a, .wav)",
            "2. 點擊 **開始處理** 按鈕",
            "3. 監控轉錄和摘要過程",
            "4. 當結果準備好時，您可以查看並下載"
        ],
        "control_panel": "控制面板",
        "select_audio": "🎵 選擇音頻文件",
        "file_name": "文件名",
        "size": "大小",
        "start_button": "🚀 開始處理",
        "stop_button": "🛑 停止",
        "recent_processes": "最近的處理",
        "no_processes": "尚無處理",
        "download_transcription": "下載轉錄",
        "download_summary": "下載摘要",
        "processing": "處理中...",
        "audio_converting": "🔄 轉換音頻文件...",
        "audio_splitting": "✂️ 將音頻文件分割成片段...",
        "transcribing": "🎤 轉錄中...",
        "transcribing_segment": "🎤 轉錄：處理片段 {}/{}",
        "summarizing": "📝 摘要文本（這可能需要一段時間）...",
        "summarizing_model": "🧠 使用 {} 模型創建綜合摘要...",
        "summary_success": "✅ 摘要成功創建！",
        "summary_short": "⚠️ 摘要創建但比預期短",
        "fallback_model": "⚠️ 無法使用主要模型創建摘要。切換到備用模型...",
        "comprehensive_summary": "✅ 綜合摘要完成！",
        "simple_summary": "⚠️ 簡單摘要完成（無法創建綜合摘要）",
        "summary_error": "❌ 摘要創建錯誤！",
        "saving_results": "💾 保存結果...",
        "process_completed": "✅ 處理完成！",
        "process_completed_message": "轉錄和摘要過程成功完成！",
        "transcription_error": "轉錄過程失敗。檢查您的音頻文件或嘗試其他文件。",
        "process_failed": "處理失敗",
        "process_stopped": "處理被用戶停止。",
        "process_error": "處理過程中出錯：{}",
        "summary_tab": "📝 摘要",
        "transcription_tab": "🎤 轉錄",
        "files_tab": "📂 文件",
        "summary_header": "生成的摘要",
        "summary_info": "以下是音頻文件的摘要內容。",
        "download_summary_button": "📥 下載摘要",
        "summary_downloaded": "摘要成功下載！",
        "transcription_header": "轉錄",
        "transcription_info": "以下是音頻文件的轉錄文本。",
        "download_transcription_button": "📥 下載轉錄",
        "transcription_downloaded": "轉錄成功下載！",
        "saved_files_header": "保存的文件",
        "transcription_file": "📄 轉錄文件",
        "summary_file": "📄 摘要文件",
        "files_stored_info": "文件存儲在 '{}' 目錄中。",
        "select_language": "語言選擇",
        "summary_options": "摘要選項",
        "select_summary_mode": "選擇摘要模式",
        "basic_mode": "基本摘要",
        "enhanced_mode": "增強摘要（需要更長時間）",
        "summary_mode_help": "增強摘要更全面和詳細，但需要兩倍的時間。",
        "basic_summarizing": "🔄 創建基本摘要...",
        "enhanced_summarizing": "🧠 創建增強摘要（這可能需要更長時間）..."
    },
    "en": {
        "app_title": "S2T2S",
        "app_subtitle": "Sound-Text Conversion and Summary System",
        "instructions_title": "Instructions",
        "instructions": [
            "1. Upload your audio file (.mp3, .m4a, .wav)",
            "2. Click the **Start Process** button",
            "3. Monitor the transcription and summarization process",
            "4. When results are ready, you can review and download them"
        ],
        "control_panel": "Control Panel",
        "select_audio": "🎵 Select audio file",
        "file_name": "File Name",
        "size": "Size",
        "start_button": "🚀 Start Process",
        "stop_button": "🛑 Stop",
        "recent_processes": "Recent Processes",
        "no_processes": "No processes yet",
        "download_transcription": "Download Transcription",
        "download_summary": "Download Summary",
        "processing": "Processing...",
        "audio_converting": "🔄 Converting audio file...",
        "audio_splitting": "✂️ Splitting audio file into segments...",
        "transcribing": "🎤 Transcribing...",
        "transcribing_segment": "🎤 Transcription: Processing segment {}/{}",
        "summarizing": "📝 Summarizing text (this may take a while)...",
        "summarizing_model": "🧠 Creating comprehensive summary with {} model...",
        "summary_success": "✅ Summary successfully created!",
        "summary_short": "⚠️ Summary created but shorter than expected",
        "fallback_model": "⚠️ Could not create summary with primary model. Switching to fallback model...",
        "comprehensive_summary": "✅ Comprehensive summary completed!",
        "simple_summary": "⚠️ Simple summary completed (could not create comprehensive summary)",
        "summary_error": "❌ Summary creation error!",
        "saving_results": "💾 Saving results...",
        "process_completed": "✅ Process completed!",
        "process_completed_message": "Transcription and summarization process successfully completed!",
        "transcription_error": "Transcription process failed. Check your audio file or try another file.",
        "process_failed": "Process failed",
        "process_stopped": "Process stopped by user.",
        "process_error": "Error during process: {}",
        "summary_tab": "📝 Summary",
        "transcription_tab": "🎤 Transcription",
        "files_tab": "📂 Files",
        "summary_header": "Generated Summary",
        "summary_info": "Below is the summarized content of the audio file.",
        "download_summary_button": "📥 Download Summary",
        "summary_downloaded": "Summary downloaded successfully!",
        "transcription_header": "Transcription",
        "transcription_info": "Below is the transcription text of the audio file.",
        "download_transcription_button": "📥 Download Transcription",
        "transcription_downloaded": "Transcription downloaded successfully!",
        "saved_files_header": "Saved Files",
        "transcription_file": "📄 Transcription File",
        "summary_file": "📄 Summary File",
        "files_stored_info": "Files are stored in the '{}' directory.",
        "select_language": "Language Selection",
        "summary_options": "Summary Options",
        "select_summary_mode": "Select summary mode",
        "basic_mode": "Basic Summary",
        "enhanced_mode": "Enhanced Summary (Takes longer)",
        "summary_mode_help": "Enhanced summary is more comprehensive and detailed, but takes twice as long.",
        "basic_summarizing": "🔄 Creating basic summary...",
        "enhanced_summarizing": "🧠 Creating enhanced summary (this may take longer)..."
    }
}

def get_text(lang, key):
    """Returns the text for the specified language and key."""
    if lang not in LANGUAGES:
        lang = "en"  
    
    return LANGUAGES[lang].get(key, f"Missing text: {key}")