LANGUAGES = {
    "tr": {
        "app_title": "S2T2S",
        "app_subtitle": "Ses-Metin Dönüşüm ve Özetleme Sistemi",
        "instructions_title": "Talimatlar",
        "instructions": [
            "1. Ses dosyanızı yükleyin (.mp3, .m4a, .wav)",
            "2. **İşlemi Başlat** butonuna tıklayın",
            "3. Transkripsiyon ve özetleme sürecini takip edin",
            "4. Sonuçlar hazır olduğunda inceleyip indirebilirsiniz"
        ],
        "control_panel": "Kontrol Paneli",
        "select_audio": "🎵 Ses dosyası seçin",
        "file_name": "Dosya Adı",
        "size": "Boyut",
        "start_button": "🚀 İşlemi Başlat",
        "stop_button": "🛑 Durdur",
        "recent_processes": "Son İşlemler",
        "no_processes": "Henüz işlem yapılmamış",
        "download_transcription": "Transkripsiyon İndir",
        "download_summary": "Özet İndir",
        "processing": "İşlem devam ediyor...",
        "audio_converting": "🔄 Ses dosyası dönüştürülüyor...",
        "audio_splitting": "✂️ Ses dosyası parçalara bölünüyor...",
        "transcribing": "🎤 Transkripsiyon yapılıyor...",
        "transcribing_segment": "🎤 Transkripsiyon: Segment {}/{}",
        "summarizing": "📝 Metin özetleniyor (bu işlem biraz sürebilir)...",
        "summarizing_model": "🧠 {} modeli ile kapsamlı özet oluşturuluyor...",
        "summary_success": "✅ Özet başarıyla oluşturuldu!",
        "summary_short": "⚠️ Özet oluşturuldu ancak beklenenden kısa",
        "fallback_model": "⚠️ Ana model ile özet oluşturulamadı. Yedek modele geçiliyor...",
        "comprehensive_summary": "✅ Kapsamlı özet tamamlandı!",
        "simple_summary": "⚠️ Basit özet tamamlandı (kapsamlı özet oluşturulamadı)",
        "summary_error": "❌ Özet oluşturma hatası!",
        "saving_results": "💾 Sonuçlar kaydediliyor...",
        "process_completed": "✅ İşlem tamamlandı!",
        "process_completed_message": "Transkripsiyon ve özetleme işlemi başarıyla tamamlandı!",
        "transcription_error": "Transkripsiyon işlemi başarısız oldu. Ses dosyasını kontrol edin veya başka bir dosya deneyin.",
        "process_failed": "İşlem başarısız",
        "process_stopped": "İşlem kullanıcı tarafından durduruldu.",
        "process_error": "İşlem sırasında hata oluştu: {}",
        "summary_tab": "📝 Özet",
        "transcription_tab": "🎤 Transkripsiyon",
        "files_tab": "📂 Dosyalar",
        "summary_header": "Oluşturulan Özet",
        "summary_info": "Aşağıda ses dosyasının özetlenmiş içeriği yer almaktadır.",
        "download_summary_button": "📥 Özeti İndir",
        "summary_downloaded": "Özet başarıyla indirildi!",
        "transcription_header": "Transkripsiyon",
        "transcription_info": "Aşağıda ses dosyasının transkripsiyon metni yer almaktadır.",
        "download_transcription_button": "📥 Transkripsiyonu İndir",
        "transcription_downloaded": "Transkripsiyon başarıyla indirildi!",
        "saved_files_header": "Kaydedilen Dosyalar",
        "transcription_file": "📄 Transkripsiyon Dosyası",
        "summary_file": "📄 Özet Dosyası",
        "files_stored_info": "Dosyalar '{}' dizininde saklanıyor.",
        "select_language": "Dil Seçimi",
        "summary_options": "Özet Seçenekleri",
        "select_summary_mode": "Özet modunu seçin",
        "basic_mode": "Temel Özet",
        "enhanced_mode": "Gelişmiş Özet (Daha uzun sürer)",
        "summary_mode_help": "Gelişmiş özet daha kapsamlı ve detaylı, ancak 2 kat daha uzun sürer.",
        "basic_summarizing": "🔄 Temel özet oluşturuluyor...",
        "enhanced_summarizing": "🧠 Gelişmiş özet oluşturuluyor (bu işlem daha uzun sürebilir)..."
    },
    "en": {
        "app_title": "S2T2S",
        "app_subtitle": "Sound-Text Conversion and Summary System",
        "instructions_title": "Instructions",
        "instructions": [
            "1. Upload your audio file (.mp3, .m4a, .wav)",
            "2. Click the **Start Process** button",
            "3. Monitor the transcription and summarization progress",
            "4. Once results are ready, you can review and download them"
        ],
        "control_panel": "Control Panel",
        "select_audio": "🎵 Select audio file",
        "file_name": "File Name",
        "size": "Size",
        "start_button": "🚀 Start Process",
        "stop_button": "🛑 Stop",
        "recent_processes": "Recent Processes",
        "no_processes": "No processes yet",
        "download_transcription": "Download Transcription",
        "download_summary": "Download Summary",
        "processing": "Processing...",
        "audio_converting": "🔄 Converting audio file...",
        "audio_splitting": "✂️ Splitting audio into segments...",
        "transcribing": "🎤 Transcribing...",
        "transcribing_segment": "🎤 Transcribing: Segment {}/{}",
        "summarizing": "📝 Summarizing text (this may take a while)...",
        "summarizing_model": "🧠 Creating comprehensive summary with {} model...",
        "summary_success": "✅ Summary created successfully!",
        "summary_short": "⚠️ Summary created but shorter than expected",
        "fallback_model": "⚠️ Could not create summary with primary model. Switching to fallback...",
        "comprehensive_summary": "✅ Comprehensive summary completed!",
        "simple_summary": "⚠️ Simple summary completed (could not create comprehensive)",
        "summary_error": "❌ Summary creation error!",
        "saving_results": "💾 Saving results...",
        "process_completed": "✅ Process completed!",
        "process_completed_message": "Transcription and summarization process completed successfully!",
        "transcription_error": "Transcription process failed. Please check your audio file or try another one.",
        "process_failed": "Process failed",
        "process_stopped": "Process stopped by user.",
        "process_error": "Error during process: {}",
        "summary_tab": "📝 Summary",
        "transcription_tab": "🎤 Transcription",
        "files_tab": "📂 Files",
        "summary_header": "Generated Summary",
        "summary_info": "Below is the summarized content of the audio file.",
        "download_summary_button": "📥 Download Summary",
        "summary_downloaded": "Summary downloaded successfully!",
        "transcription_header": "Transcription",
        "transcription_info": "Below is the transcription text of the audio file.",
        "download_transcription_button": "📥 Download Transcription",
        "transcription_downloaded": "Transcription downloaded successfully!",
        "saved_files_header": "Saved Files",
        "transcription_file": "📄 Transcription File",
        "summary_file": "📄 Summary File",
        "files_stored_info": "Files are stored in the '{}' directory.",
        "select_language": "Language Selection",
        "summary_options": "Summary Options",
        "select_summary_mode": "Select summary mode",
        "basic_mode": "Basic Summary",
        "enhanced_mode": "Enhanced Summary (Takes longer)",
        "summary_mode_help": "Enhanced summary is more comprehensive and detailed but takes twice as long.",
        "basic_summarizing": "🔄 Creating basic summary...",
        "enhanced_summarizing": "🧠 Creating enhanced summary (this may take longer)..."
    },
    "zh": {
        "app_title": "S2T2S",
        "app_subtitle": "语音文本转换与摘要系统",
        "instructions_title": "使用说明",
        "instructions": [
            "1. 上传您的音频文件 (.mp3, .m4a, .wav)",
            "2. 点击**开始处理**按钮",
            "3. 监控转录和摘要处理进度",
            "4. 结果准备就绪后，您可以查看和下载"
        ],
        "control_panel": "控制面板",
        "select_audio": "🎵 选择音频文件",
        "file_name": "文件名",
        "size": "大小",
        "start_button": "🚀 开始处理",
        "stop_button": "🛑 停止",
        "recent_processes": "最近处理",
        "no_processes": "暂无处理记录",
        "download_transcription": "下载转录文本",
        "download_summary": "下载摘要",
        "processing": "处理中...",
        "audio_converting": "🔄 正在转换音频文件...",
        "audio_splitting": "✂️ 正在将音频文件分段...",
        "transcribing": "🎤 正在转录...",
        "transcribing_segment": "🎤 转录：正在处理片段 {}/{}",
        "summarizing": "📝 正在生成文本摘要（可能需要一些时间）...",
        "summarizing_model": "🧠 正在使用 {} 模型创建全面摘要...",
        "summary_success": "✅ 摘要生成成功！",
        "summary_short": "⚠️ 摘要已生成但比预期短",
        "fallback_model": "⚠️ 无法使用主要模型创建摘要。正在切换到备用模型...",
        "comprehensive_summary": "✅ 全面摘要完成！",
        "simple_summary": "⚠️ 简单摘要完成（无法创建全面摘要）",
        "summary_error": "❌ 摘要生成错误！",
        "saving_results": "💾 正在保存结果...",
        "process_completed": "✅ 处理完成！",
        "process_completed_message": "转录和摘要处理已成功完成！",
        "transcription_error": "转录处理失败。请检查您的音频文件或尝试其他文件。",
        "process_failed": "处理失败",
        "process_stopped": "处理已被用户停止。",
        "process_error": "处理过程中出错：{}",
        "summary_tab": "📝 摘要",
        "transcription_tab": "🎤 转录",
        "files_tab": "📂 文件",
        "summary_header": "生成的摘要",
        "summary_info": "以下是音频文件的摘要内容。",
        "download_summary_button": "📥 下载摘要",
        "summary_downloaded": "摘要下载成功！",
        "transcription_header": "转录",
        "transcription_info": "以下是音频文件的转录文本。",
        "download_transcription_button": "📥 下载转录",
        "transcription_downloaded": "转录下载成功！",
        "saved_files_header": "已保存的文件",
        "transcription_file": "📄 转录文件",
        "summary_file": "📄 摘要文件",
        "files_stored_info": "文件存储在 '{}' 目录中。",
        "select_language": "语言选择",
        "summary_options": "摘要选项",
        "select_summary_mode": "选择摘要模式",
        "basic_mode": "基础摘要",
        "enhanced_mode": "增强摘要（需要更长时间）",
        "summary_mode_help": "增强摘要更加全面和详细，但需要两倍的处理时间。",
        "basic_summarizing": "🔄 正在创建基础摘要...",
        "enhanced_summarizing": "🧠 正在创建增强摘要（可能需要更长时间）..."
    }
}

def get_text(lang, key):
    """Returns the text for the specified language and key."""
    if lang not in LANGUAGES:
        lang = "tr"  
    
    return LANGUAGES[lang].get(key, f"Missing text: {key}")